### ISSUE TITLE
Use python package logging for adjustable debug/info output

### ISSUE THREAD

**Issue by dkriegner** [dkriegner/micro-flakes#12]
We could use https://docs.python.org/3/library/logging.html
to allow for an easily adjustable degree of logging output. The user could via a command line argument set the level of verbosity they expect in the output.

**Comment by ji-ze** [comment]
Info messages don't show in the terminal. After using `logging.getLogger().setLevel(logging.INFO)`, all messages are red:
<img width="469" alt="image" src="https://github.com/dkriegner/micro-flakes/assets/44098973/4e4e5fec-6af1-4bd7-96d0-c7e9b76d7149">

**Comment by dkriegner** [comment]
> How to rewrite this:
> 
> https://github.com/dkriegner/micro-flakes/blob/5bfe2fec0c2221210179c23176917f3028dc7a71/Detector/find_objects.py#L243

I am not sure myself. Its possible that this can not be rewritten since a log entry is always a separate line

**Comment by dkriegner** [comment]
> Info messages don't show in the terminal. After using `logging.getLogger().setLevel(logging.INFO)`, all messages are red: <img alt="image" width="469" src="https://user-images.githubusercontent.com/44098973/283863269-4e4e5fec-6af1-4bd7-96d0-c7e9b76d7149.png">

I am pretty sure this is a particularity of your command line. usually info output is not red. Warnings/errors might be red. In my command line actually no logging output is red. There are lots of things which can be configured via the "handler" of the logger

**Comment by ji-ze** [comment]
I've just tried to open in the Windows terminal:

<img width="960" alt="image" src="https://github.com/dkriegner/micro-flakes/assets/44098973/8de7bfb7-acea-48f7-86d5-017d5b137f14">

It doesn't look terrible.

**Comment by dkriegner** [comment]
I do not like much the `INFO:root:` part. you can remove this as outlined for example here:

**Comment by ji-ze** [comment]
It works!
<img width="568" alt="image" src="https://github.com/dkriegner/micro-flakes/assets/44098973/0ae01023-e5da-4ce2-b4ea-3bde69a338ad">
