### ISSUE TITLE
github action to automatically testrun the code

### ISSUE THREAD

**Issue by dkriegner** [dkriegner/micro-flakes#14]
To keep the code running with future changes we should think of some test code which should cover at least the core functionality. 

Now that the code can take command line options and no interactive input is needed this should be possible by running the main script with some reasonable input. The github action could than maybe also test if an appropriate output is generated.

**Comment by dkriegner** [comment]
for this to work we need that the script can run without user interference/input. This is now already possible with 

`flakes-detector -p Samples_for_testing -n calibration.jpg`

but the problem is that at the end of the script it requires to press enter. I propose to add a new command line switch (e.g. `-q/--quiet` to disable the need for this input.

**Comment by ji-ze** [comment]
I have edited the code:
`    parser.add_argument("-q", "--quiet",
                        default=False,
                        help="The detector will close after processing an input picture without the user input",
                        type=bool)
`

**Comment by dkriegner** [comment]
I activated the automatic test run. It should run on every push or pull request to the main branch
