### ISSUE TITLE
CACHE file is generated in the current working folder.

### ISSUE THREAD

**Issue by dkriegner** [dkriegner/micro-flakes#19]
I believe the CACHE file needs to be generated in one and the same place, but not in the folder where I execute the script.

**Comment by ji-ze** [comment]
I tried to use `os.path.dirname(__file__)`, but it doesn't work for an exe-file. It uses the path: .../AppData/local/... After restarting the script, CACHE is created new.

**Comment by ji-ze** [comment]
Is it a good idea if the script stores the cache file to C:\Users\{username}\AppData\Local\{appname}?

**Comment by ji-ze** [comment]
```
import os
import inspect

def get_script_dir():
    # Try to use __file__ attribute
    try:
        return os.path.dirname(os.path.abspath(__file__))
    # If __file__ is not defined, use inspect module
    except NameError:
        return os.path.dirname(os.path.abspath(inspect.getsourcefile(get_script_dir)))

# Print the script directory
print(get_script_dir())
```

**Comment by ji-ze** [comment]
```
import os
import sys

# Get the path of the executable file
exe_path = sys.executable
print("The path of the executable file is:", exe_path)

# Get the directory name from the path
exe_dir = os.path.dirname(exe_path)
print("The directory of the executable file is:", exe_dir)

```

**Comment by dkriegner** [comment]
Two problems I see:

1) I believe this only works in windows and potentially only when using pyinstaller. In linux I get
```
$ python GUI/Test.py 
The path of the executable file is: /usr/bin/python
The directory of the executable file is: /usr/bin
Press a key!
```
And /usr/bin is certainly not the directly the CACHE should be placed in. I would say C:/Users/{username}/AppData/Local/{appname} sounds good for Windows. In 
2) The command line app still uses the executation directory to store the CACHE

Maybe one could use this package to simplify your life:
https://github.com/platformdirs/platformdirs

It would work on all platforms like this:
```python
import platformdirs
platformdirs.user_config_dir("micro-flakes")
```

**Comment by dkriegner** [comment]
Also I believe the CACHE file should likely be compatible with the [configparser](https://docs.python.org/3/library/configparser.html) package. this allows to specify fallback values and make type conversion more straight-forwardly

**Comment by ji-ze** [comment]
I integrated the [configparser](https://docs.python.org/3/library/configparser.html) to the code.
