### ISSUE TITLE
setValue() sets only two decimals

### ISSUE THREAD

**Issue by ji-ze** [dkriegner/micro-flakes#23]
https://github.com/dkriegner/micro-flakes/blob/3d5cb42e78c1213a4b3f4a58cedd411fccefe634/GUI/main.py#L269C1-L270C1

**Comment by dkriegner** [comment]
you have to first change the number of digits and only after you can set a value with a higher precision. Should be fixed by [160de3d](https://github.com/dkriegner/micro-flakes/commit/160de3d3b5f9b144ea3d086a47d5e1c1be621278)
