### ISSUE TITLE
split data and code

### ISSUE THREAD

**Issue by dkriegner** [dkriegner/micro-flakes#4]
we will have to find a solution to split the data (images and output files) from the code.
 
Likely after issue #3 is solved this will be rather straigt forward

**Comment by ji-ze** [comment]
I solved it.

**Comment by ji-ze** [comment]
Is it current?

**Comment by dkriegner** [comment]
The issue itself is solved. I close it.

As a note to myself: we need a shared datastorage for the pictures. but it is disconnected from the github repository
