### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by ji-ze** [dkriegner/micro-flakes#9]
Helena suggests it'd be better if the program had a graphical interface. I've tried to use  tkinter,  but it doesn't work for me well.

**Comment by ji-ze** [comment]
I've tried to use PyQt6. My code is:
```
from PyQt6.QtWidgets import QApplication, QWidget, QVBoxLayout, QPushButton, QTextEdit, QComboBox, QLabel, QPlainTextEdit, QFileDialog
import sys

class MyApp(QWidget):
    def __init__(self):
        super().__init__()

        self.initUI()

    def initUI(self):
        vbox = QVBoxLayout()
        self.setLayout(vbox)

        self.label1 = QLabel('Welcome in software to automatic detect flakes in a microscope.')
        vbox.addWidget(self.label1)

        self.label2 = QLabel('Please select a source of input data:')
        vbox.addWidget(self.label2)

        self.button1 = QPushButton('Take a new photo of samples')
        self.button1.clicked.connect(self.open_option1)
        vbox.addWidget(self.button1)

        self.button2 = QPushButton('Load a photo of samples')
        self.button2.clicked.connect(self.open_option2)
        vbox.addWidget(self.button2)

        self.setWindowTitle('Flakes detector')
        self.setGeometry(300, 300, 300, 200)
        self.show()

    def open_option1(self):
        self.option1 = Option1()

    def open_option2(self):
        self.option2 = Option2()

class Option1(QWidget):
    def __init__(self):
        super().__init__()

        self.initUI()

    def initUI(self):
        vbox = QVBoxLayout()
        self.setLayout(vbox)

        self.label = QLabel('Enter Information:')
        vbox.addWidget(self.label)

        self.textbox = QTextEdit()
        vbox.addWidget(self.textbox)

        self.combobox = QComboBox()
        self.combobox.addItems(["Option 1", "Option 2", "Option 3"])
        vbox.addWidget(self.combobox)

        self.dirButton = QPushButton('Choose Directory')
        self.dirButton.clicked.connect(self.open_directory_dialog)
        vbox.addWidget(self.dirButton)

        self.button = QPushButton('Press Me')
        self.button.clicked.connect(self.on_click)
        vbox.addWidget(self.button)

        self.logbox = QPlainTextEdit()
        self.logbox.setReadOnly(True)
        vbox.addWidget(self.logbox)

        self.setWindowTitle('Option 1')
        self.setGeometry(300, 300, 300, 200)
        self.show()

    def open_directory_dialog(self):
        options = QFileDialog.Options()
        directory = QFileDialog.getExistingDirectory(self, "QFileDialog.getExistingDirectory()", "", options=options)
        if directory:
            self.logbox.appendPlainText(f'User selected directory: {directory}')
        else:
            self.logbox.appendPlainText('No directory selected.')

    def on_click(self):
        text = self.textbox.toPlainText()
        option = self.combobox.currentText()
        self.logbox.appendPlainText(f'User entered: {text}')
        self.logbox.appendPlainText(f'User selected: {option}')


class Option2(QWidget):
    def __init__(self):
        super().__init__()

        self.initUI()

    def initUI(self):
        vbox = QVBoxLayout()
        self.setLayout(vbox)

        self.label = QLabel('Choose a File:')
        vbox.addWidget(self.label)

        self.button = QPushButton('Choose File')
        self.button.clicked.connect(self.open_file_dialog)
        vbox.addWidget(self.button)

        self.logbox = QPlainTextEdit()
        self.logbox.setReadOnly(True)
        vbox.addWidget(self.logbox)

        self.setWindowTitle('Option 2')
        self.setGeometry(300, 300, 300, 200)
        self.show()

    def open_file_dialog(self):
        options = QFileDialog.Options()
        fileName, _ = QFileDialog.getOpenFileName(self, "QFileDialog.getOpenFileName()", "",
                                                  "All Files (*);;Python Files (*.py)", options=options)
        if fileName:
            self.logbox.appendPlainText(f'User selected file: {fileName}')
        else:
            self.logbox.appendPlainText('No file selected.')


if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = MyApp()
    sys.exit(app.exec())

```

After click on Choose File, the script falls with "Process finished with exit code -1073740791 (0xC0000409)"
I asked GPT. Its answer is:
"[The error code -1073740791 (0xC0000409) typically indicates a STATUS_STACK_BUFFER_OVERRUN](https://stackoverflow.com/questions/49432873/process-finished-with-exit-code-1073740791-0xc0000409-status-stack-buffer-ove)[1](https://stackoverflow.com/questions/49432873/process-finished-with-exit-code-1073740791-0xc0000409-status-stack-buffer-ove). [This error can occur when a program writes more data to a block of memory, or buffer, than it can hold, or when a program writes data to a memory area past a buffer](https://stackoverflow.com/questions/49432873/process-finished-with-exit-code-1073740791-0xc0000409-status-stack-buffer-ove)[1](https://stackoverflow.com/questions/49432873/process-finished-with-exit-code-1073740791-0xc0000409-status-stack-buffer-ove). [In this case, it’s likely that the error is being caused by a problem with the PyQt6 library or one of its dependencies](https://stackoverflow.com/questions/49432873/process-finished-with-exit-code-1073740791-0xc0000409-status-stack-buffer-ove)[1](https://stackoverflow.com/questions/49432873/process-finished-with-exit-code-1073740791-0xc0000409-status-stack-buffer-ove).

Here are a few potential solutions you could try:

[Update your PyQt6 library to the latest version](https://stackoverflow.com/questions/49432873/process-finished-with-exit-code-1073740791-0xc0000409-status-stack-buffer-ove)[1](https://stackoverflow.com/questions/49432873/process-finished-with-exit-code-1073740791-0xc0000409-status-stack-buffer-ove).
[If you’re using other libraries that interact with PyQt6, such as numpy or tensorflow, make sure they’re also updated to the latest version](https://stackoverflow.com/questions/49432873/process-finished-with-exit-code-1073740791-0xc0000409-status-stack-buffer-ove)[1](https://stackoverflow.com/questions/49432873/process-finished-with-exit-code-1073740791-0xc0000409-status-stack-buffer-ove).
[If you’re using an Intel GPU, you might need to update your drivers](https://stackoverflow.com/questions/49432873/process-finished-with-exit-code-1073740791-0xc0000409-status-stack-buffer-ove)[1](https://stackoverflow.com/questions/49432873/process-finished-with-exit-code-1073740791-0xc0000409-status-stack-buffer-ove).
[If you’re using a NVIDIA GPU, make sure you have the correct version of CUDA installed](https://stackoverflow.com/questions/49432873/process-finished-with-exit-code-1073740791-0xc0000409-status-stack-buffer-ove)[1](https://stackoverflow.com/questions/49432873/process-finished-with-exit-code-1073740791-0xc0000409-status-stack-buffer-ove).
[If none of these solutions work, you might want to consider asking for help on a Python or PyQt6 forum, providing them with the exact error message and the code you’re trying to run](https://stackoverflow.com/questions/49432873/process-finished-with-exit-code-1073740791-0xc0000409-status-stack-buffer-ove)[1](https://stackoverflow.com/questions/49432873/process-finished-with-exit-code-1073740791-0xc0000409-status-stack-buffer-ove). [They might be able to provide more specific advice based on your particular situation](https://stackoverflow.com/questions/49432873/process-finished-with-exit-code-1073740791-0xc0000409-status-stack-buffer-ove)[1](https://stackoverflow.com/questions/49432873/process-finished-with-exit-code-1073740791-0xc0000409-status-stack-buffer-ove). I hope this helps! 😊"

**Comment by ji-ze** [comment]
I've solved it. The problem was in "options".

**Comment by dkriegner** [comment]
`if __name__ == '__main__':`

This line is again a sign you do not use the `pyproject.toml` installer. This should instead be

`def main():`

and in pyproject.toml you need to add a `[project.gui-scripts]` section. The documentation can be found [here](https://flit.pypa.io/en/latest/pyproject_toml.html#scripts-section)

I also believe that your main window should be derived from `QMainWindow` which has more options.

**Comment by ji-ze** [comment]
I've uploaded the GUI version to the GUI folder. It's the version of the discussion.  Now, I focused on optimise terminal version. I'll implement the GUI in the final version.
 
![image](https://github.com/dkriegner/micro-flakes/assets/44098973/1d38b14c-d3b2-4049-a355-cc13f4d1ee49)
![image](https://github.com/dkriegner/micro-flakes/assets/44098973/468eccd6-0eb5-4deb-927c-1de747728eae)

**Comment by dkriegner** [comment]
This already looks like a good start. As far as I see this still uses the excel table as an output which maybe in a later version we would want to replace by some possible output in the GUI. I am also not sure if it would not be benefitial to try to have all in one window. What is the advantage of splitting it into two windows?

Most importantly: Please do not copy the code. The GUI code should be integrated in the main python package. So there should be not extra GUI folder. I believe this is not necessary and the duplication of the code will make maintaining it much harder.

**Comment by ji-ze** [comment]
OK. I agree.
Where I store the GUI and exe version?

**Comment by ji-ze** [comment]
I removed the GUI folder. I created GUI_main.py in "Detector". It works:

https://github.com/dkriegner/micro-flakes/assets/44098973/d2913ef1-6264-459a-a461-32e2201e74ed

**Comment by ji-ze** [comment]
> This already looks like a good start. As far as I see this still uses the excel table as an output which maybe in a later version we would want to replace by some possible output in the GUI. I am also not sure if it would not be benefitial to try to have all in one window. What is the advantage of splitting it into two windows?
> 
> Most importantly: Please do not copy the code. The GUI code should be integrated in the main python package. So there should be not extra GUI folder. I believe this is not necessary and the duplication of the code will make maintaining it much harder.

Is it better?
https://github.com/dkriegner/micro-flakes/blob/4700d5cfa7de77a9d7eff278c5c326e6faf95030/Flakes%20Detector%20GUI%20Windows.zip

**Comment by dkriegner** [comment]
the video looks great. I have only minor suggestions we can discuss tomorrow. 

I believe the zip file should not be inside the code. it should only be in the downloads for the release.
